#!/bin/bash
echo -e "\nNOTICE: This script has been tested only on Ubunbu 20.04 and 22.04\n"
os=$(lsb_release -rs)
os=${os:0:5}
if [ ! $os == "20.04" ] && [ ! $os == "22.04" ]
then
	echo "OS release $os detected and is an unsupported Linux release"
	echo "Script terminating and was unsucessful."
	exit 1
fi

if [ ! `whoami` == "root" ]
then
	echo "Execute this script as root:"
	echo "sudo $0"
	exit 1
fi

echo -e "This script will attempt to install a number of packages on this system.\n"
if [ ! -f Gemfile  ]
	then
		echo -e "\nCreating a simple Gemfile to aid in installing Cucumber"
		echo -e "source 'https://rubygems.org'\ngroup :test do\n\tgem 'cucumber'\n\tgem 'aruba'\nend\n" >Gemfile
fi
# Update the list of packages
sudo apt-get update
# Install pre-requisite packages.
sudo apt-get install -y wget apt-transport-https software-properties-common
# Download the Microsoft repository GPG keys
wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
# Register the Microsoft repository GPG keys
sudo dpkg -i packages-microsoft-prod.deb
# Update the list of packages after we added packages.microsoft.com
sudo apt-get update
# Install apps including PowerShell

if [ $os == "20.04" ] 
then
sudo apt-get -y install ruby-full ruby-build ruby-dev build-essential powershell python2 python3 python lynx locales locales-all vim nano sqlite3
fi

if [ $os == "22.04" ] 
then
sudo apt-get -y install ruby-full ruby-build ruby-dev build-essential powershell python2 python3 2to3 python2-minimal python2 dh-python python-is-python3 lynx locales locales-all vim nano sqlite3
fi

sudo echo 'America/Denver' > /etc/timezone
sudo rm /etc/localtime
sudo dpkg-reconfigure -f noninteractive tzdata
sudo locale-gen en_US.UTF-8
sudo update-locale LANG=en_US.UTF-8


echo "Installing bundler..."
sudo gem install bundler
sudo bundle update
echo -e "\n\nCS 3030 assignments can now be completed and tested on this system"
echo -e "\n\nYou need to close this terminal window and open a new one."
echo -e "\n\nDo not execute cucumber as root"
